# Generated by Django 3.2.7 on 2021-10-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20211006_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_ftd',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
