# Generated by Django 3.2.7 on 2021-10-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_is_ftd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='is_ftd',
        ),
        migrations.AddField(
            model_name='lead',
            name='deposit',
            field=models.BooleanField(default=False),
        ),
    ]
